# Generated by Django 5.0 on 2023-12-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_job', models.CharField(max_length=100)),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_job', models.CharField(max_length=100)),
                ('have_siblings', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
