# Generated by Django 5.0 on 2023-12-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_api', '0003_sibling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_job', models.CharField(max_length=100)),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_job', models.CharField(max_length=100)),
                ('have_siblings', models.BooleanField()),
                ('parent_contact_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('other_role', models.CharField(blank=True, choices=[('prefect', 'Prefect'), ('class_leader', 'Class Leader'), ('cadet', 'Cadet'), ('rirst_aid', 'First aid'), ('media_unit', 'Media Unit'), ('environmental_officer', 'Environmental Officer'), ('the_band', 'The Band'), ('others', 'Others')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sibling',
            name='sibling_grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sibling',
            name='sibling_index_num',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='student_management_api.student')),
            ],
        ),
        migrations.AlterField(
            model_name='sibling',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='student_management_api.student'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
