# Generated by Django 5.0 on 2023-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_api', '0004_student_sibling_sibling_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('prefect', 'Prefect'), ('class_leader', 'Class Leader'), ('cadet', 'Cadet'), ('first_aid', 'First Aid'), ('media_unit', 'Media Unit'), ('environmental_officer', 'Environmental Officer'), ('the_band', 'The Band'), ('others', 'Others')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_role',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='other_roles',
            field=models.ManyToManyField(blank=True, related_name='students', to='student_management_api.role'),
        ),
    ]
